name: CI
on:
  issues:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show GITHUB_EVENT_NAME
        run: echo $GITHUB_EVENT_NAME
      - name: Show env
        run: env
      - name: Show $GITHUB_EVENT_PATH
        run: cat $GITHUB_EVENT_PATH
